"""users and posts update

Revision ID: 1bd98e7935eb
Revises: 9f8d914c2566
Create Date: 2024-01-29 00:31:38.480305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bd98e7935eb'
down_revision: Union[str, None] = '9f8d914c2566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.drop_column('posts', 'created')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('created', sa.DATETIME(), nullable=False))
    op.drop_column('posts', 'created_at')
    # ### end Alembic commands ###
